# Generated by Django 5.0.1 on 2024-02-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlCliente', '0002_cliente_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
