# Generated by Django 5.0.1 on 2024-02-04 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlCliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('pdf', models.TextField(blank=True, null=True)),
                ('total_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlCliente.cliente')),
                ('id_servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlCliente.servicio')),
            ],
            options={
                'db_table': 'pago',
                'managed': True,
            },
        ),
    ]
