# Generated by Django 5.0.1 on 2024-02-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
                ('disco', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=10)),
                ('procesador', models.CharField(max_length=50)),
                ('uso_disco', models.CharField(blank=True, max_length=15, null=True)),
                ('ip_local', models.CharField(max_length=15)),
                ('anydesk', models.CharField(max_length=12)),
                ('nom_usuario', models.CharField(max_length=50)),
                ('nom_antivirus', models.CharField(max_length=20)),
                ('vig_antivirus', models.DateField()),
                ('office', models.CharField(max_length=30)),
                ('vig_office', models.DateField()),
                ('descripcion', models.TextField(blank=True, max_length=600, null=True)),
            ],
            options={
                'db_table': 'equipo',
                'managed': True,
            },
        ),
    ]
