# Generated by Django 5.0.1 on 2024-02-04 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlCliente', '0001_initial'),
        ('controlSoporte', '0002_rename_disco_equipo_tipo_disco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='id_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlCliente.cliente'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlCliente.servicio'),
        ),
    ]
