# Generated by Django 5.0.1 on 2024-01-31 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlCliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contrato', models.DateField(blank=True, null=True)),
                ('vigencia_contrato', models.DateField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlCliente.cliente')),
                ('id_servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlCliente.servicio')),
            ],
            options={
                'db_table': 'contrato',
                'managed': True,
            },
        ),
    ]
